name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Build the Docker image
      uses: actions/checkout@v3
    
    - name: Setup node 
      uses: actions/setup-node@v2
      with: 
        node-version:  '18.x'
        
    - name: NPM Install
      run: npm install
      
    - name: Run Lint Code
      run: npm run lint
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dmytromyroshnyk/my-node-app:latest
      if: success()
      
    - name: Push Docker Image
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - run: docker push dmytromyroshnyk/my-node-app
      if: success()
      
    - name: Pull & Run
      run: | 
        docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
        docker run -p 80:80 --cpus="0.5" --memory="512m" -d dmytromyroshnyk/my-node-app
        sleep 5
        curl -i localhost:80
      
